### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by faker28** [WenMellors/TS-TrajGen#10]
您好！
    共有两个问题希望您能解答，
    1、train_gan.py 中使用的真实轨迹数据集是201511_week1_short_traj，而 train_region_gan.py中使用的真实轨迹数据集是201511_week1_mm_region_test.csv   ，请问这个真实轨迹数据集是用训练数据集，测试数据集还是未划分（包含所有轨迹数据）的数据集。
    2、训练中训练判别器很快，使用1个3080训练生成器（生成2000条轨迹）需要13个小时，这是否正常呢？
    若能解答，不胜感激。

**Comment by WenMellors** [comment]
您好！

感谢您对我们工作的关注！

1. 使用的是训练集数据。另外，GAN 的步骤训练不是很稳定，预训练的结果就已经很有效了。

2. 轨迹生成器的训练过程是有一点慢，因为数据量很大。一条轨迹会被切成很多段，然后做训练（如果是预训练过程的话）。若觉得太慢了，可以适当增大 batch size。

祝您科研一切顺利。
