### ISSUE TITLE
作者您好，关于您团队的另一篇文章，我想请求一下帮助。

### ISSUE THREAD

**Issue by zhanggongkai123** [WenMellors/TS-TrajGen#11]
作者您好，我是武汉大学2023级的一名研究生。

最近看到您团队所发表的NASR这篇文章，《Empowering A* Search Algorithms with Neural Networks for Personalized Route Recommendation》。您的团队在github上开源了代码，但没有放完整的数据集，代码里的所需的输入数据和所公开的云盘里的数据不一致，因此导致代码无法看懂与运行（例如trainData、trainGeoData、trainTimeData这些变量含义未知）。

我曾向几位作者发过邮件，但都没有回复。请问您可以帮忙联系下他们吗？

这篇文章我们想用来做基线，因为路径规划开源的代码非常少，所以它对我们很重要，希望您能回复我们。

祝您龙年大吉，工作愉快，生活如意，日日顺心~~~

**Comment by WenMellors** [comment]
您好。
NASR 那篇的学长早就毕业了，然后组里也没有继承到当时的代码。
此前组里尝试复现过，但效果也不是很理想。
很抱歉不能给你提供帮助。
（ps: 我也毕业了）
