### ISSUE TITLE
adjacent_list.json not found

### ISSUE THREAD

**Issue by xjmxyt** [WenMellors/TS-TrajGen#2]
I see you use adjacent_list.json in the file preprocess_pretrain_input.py, but I cannot find the file, can you provide that

**Comment by WenMellors** [comment]
Oh, it can be calculated by our data preprocecss script `preprocess_pretrain_input.py` based on the .rel file.
https://github.com/WenMellors/TS-TrajGen/blob/a71502d3a834f0069475ba3c71bb56f851e32a62/script/preprocess_pretrain_input.py#LL61C1-L76C23
