### ISSUE TITLE
请问你们可以提供更完整的数据吗？

### ISSUE THREAD

**Issue by LennyWallUp** [WenMellors/TS-TrajGen#3]
我在尝试使用你们的项目的时候遇到了许多困难，比如运行preprocess_pretrain_input.py时，发现你们没有划分训练集、测试集，我擅自划分了下；然后在下一步运行pretrain_gat_fc.py时发现，你们没有adjacent_mx.npz和node_feature.pt等文件，请问这些数据在哪里可以获取？如果是你们自己处理的数据，请问方便提供一下吗？

**Comment by WenMellors** [comment]
这两个文件可以参考 pretrain_gat_fc.py 里面对 xian 新数据集中的代码处理。
https://github.com/WenMellors/TS-TrajGen/blob/a71502d3a834f0069475ba3c71bb56f851e32a62/pretrain_gat_fc.py#L121-L141
