### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by GTGJi** [WenMellors/TS-TrajGen#4]
Hello @WenMellors, first of all I'd like to thank you (and your colleagues) for the hard work put into this library.
In the codes of the library, I found that the majority part is for the Xian's dataset to generate different prerequired files. May I ask if I can have the access to the Xian's datset by any chance? I checked the LibCity library and it showed that "Please contact the author" for the Xian trajectory dataset.

**Comment by WenMellors** [comment]
I'm afraid I can't share the Xian dataset with you. Because the Xian dataset was previously obtained through the Didi Open Source GAIA Project. However, currently Didi has not open sourced this part of the data, so we cannot open source this part of the data again.

**Comment by GTGJi** [comment]
> I'm afraid I can't share the Xian dataset with you. Because the Xian dataset was previously obtained through the Didi Open Source GAIA Project. However, currently Didi has not open sourced this part of the data, so we cannot open source this part of the data again.

Thank you! I totally understand this situation and the privacy concern.
