### ISSUE TITLE
Miss a file in the construct_region_dist.py 

### ISSUE THREAD

**Issue by GTGJi** [WenMellors/TS-TrajGen#5]
Hello @WenMellors, Thank you for the detailed guidance.
I am following your instructions to run the model based on BJ_Taxi dataset. But when I ran the construct_region_dist.py, there was one file named "xianshi_partA_traj_mm_processed.csv", but did not show where it comes from. I could not use it as a reference to deal with the BJ_Taxi dataset. 
May I have your help to explain where this CSV file is from please? Thank you so much!

**Comment by WenMellors** [comment]
It should be the trajectory CVS file. We use the length of trajectory from area A to area B to estimate the distance between area A and area B, so we need to read the trajectory CSV file
